name: run2

on:
  workflow_run:
    workflows: [first]
    types:
      - completed

jobs:
  job1:
    name: second2
    runs-on: ubuntu-latest
    steps:
      - name: Update paddle
        run: |
          echo  second2
