name: Check PR Template

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

env:
  AGILE_PULL_ID: ${{ github.event.pull_request.number }}
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install httpx

    - name: Check PR Template
      run: |
        echo aaa
